config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config 
  ActiveAdmin.routes(self)

  mount ActionCable.server => '/cable'

  devise_for :doctors, path: 'doctors'
  devise_for :patients, path: 'patients' do
    get '/patients/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'pages#home'

  patch '/appointments/:appointment_id/add_recommendation', to: 'appointments#add_recommendation', as: :recommendations

  resources :categories, only: :show
  resources :doctors, only: :show do
    resources :appointments, only: %i[show create]
  end
  resources :patients, only: :show do
    resources :appointments, only: :update
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability 
  include CanCan::Ability

  def initialize(user)
      user ||= User.new # guest user (not logged in)
      if user.is_a?(Patient)
        can :manage, Appointment
      elsif user.is_a?(Doctor)
        can :manage, Appointment
        can :manage, Doctor
      else
        can :read, Appointment
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  
  validates :phone, uniqueness: true

  def email_required?
    false
  end

  def will_save_change_to_email?
    false
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
  has_one_attached :photo

  scope :active, -> { where(status: 'active') }
  scope :closed, -> { where(status: 'closed') }

  validate :check_availability, :on => :create

  def check_availability
    if doctor.appointments.active.length > 9
      errors.add(:appointment, :blank, message: "#{doctor.name} is busy, please try later.")
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true, uniqueness: true

  has_many :doctors
end

app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :doctor
  belongs_to :patient

  has_many :messages, dependent: :destroy

end

app/models/doctor.rb
class Doctor < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  belongs_to :category
  has_many :appointments
  has_many :patients, through: :appointments

  has_many :messages, as: :messageable

  validates :phone, uniqueness: true

  def email_required?
    false
  end

  def will_save_change_to_email?
    false
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :messageable, polymorphic: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :appointments
  has_many :doctors, through: :appointments

  has_many :messages, as: :messageable

  validates :phone, uniqueness: true

  def email_required?
    false
  end

  def email_changed? 
    false
  end

  def will_save_change_to_email?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_ability
    @current_ability ||= Ability.new(current_user)
  end

  def current_user
    current_patient || current_doctor
  end

  def after_sign_in_path_for(resource)
    doctor_path(current_doctor) if current_doctor.present?
    patient_path(current_patient) if current_patient.present?
    admin_admin_user_path(current_admin_user) if current_admin_user.present?
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  load_and_authorize_resource
  
  def show
    @appointment = Appointment.find(params[:id])
  end

  def create
    @doctor = Doctor.find(params[:doctor_id])
    @appointment = current_patient.appointments.build(doctor_id: params[:doctor_id])
    if @appointment.save
      redirect_to root_path, notice: "You successfully booked an appointment"
    else
      redirect_to root_path, alert: "Ooops ... Dr. #{@doctor.name} is not available in the near future, please try later"
    end
  end
  
  def update
    @appointments = current_patient.appointments
    @appointment = @appointments.find(params[:id])
    @appointment.status = 'closed'
    if @appointment.save
      flash[:notice] = "Appointment to Dr. #{@appointment.doctor.name} was cancelled"
      redirect_to patient_path(current_patient)
    else
      flash.now[:allert] = 'Not cancelled, try again'
      render :show
    end
  end

  def add_recommendation
    @doctor = current_doctor
    @appointment = @doctor.appointments.find(params[:appointment_id])
    @appointment.photo.attach(params[:appointment][:photo]) if !params[:appointment][:photo].nil?
    if @appointment.update(recommendation: params[:appointment][:recommendation], status: 'closed')
      flash[:notice] = "Recommendation was successfully created"
      redirect_to doctor_path(@doctor)
    else
      render :show
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    doctor_ids = @category.doctors.ids
    @doctors = Doctor.find(doctor_ids)
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def show
    @doctor = Doctor.find(params[:id])
    @appointments = @doctor.appointments if current_doctor.present?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home; end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  def show
    @patient = patient_signed_in? ? current_patient : Patient.find(params[:id])
    @appointments = @patient.appointments
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin_users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin_users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:phone) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/appointments/show.html.erb
<%= form_with( model: @appointment, url: recommendations_path(@appointment), method: :patch) do |form| %>
  <%= form.label :recommendation, "Recommendations:" %>
  <%= form.text_field :recommendation %>
  <%= form.file_field :photo %>
  <%= form.submit "Submit" %>
<% end %>

app/views/categories/index.html.erb
<div class="cat--header">
  <h1>Find local doctors with the shortest wait time</h1>
</div>

<div class="cat--container">
  <ul>
    <% @categories.each do |category| %>
      <li>
        <div class="cat--item">
          <%= link_to category.title, category_path(category) %>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/categories/show.html.erb
<div class="cat--show-container">
  <h3>Book top <%= @category.title%>s near me</h3>
  <ul>
    <% @doctors.each do |doctor| %>
      <li>
        <div class="cat--show-header">
          <p class="cat--show-title">Dr. <%= link_to doctor.name, doctor_path(doctor) %></p>
          <p class="cat--show-phone">cell: +<%= doctor.phone %></p>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/doctors/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/doctors/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:phone) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/doctors/show.html.erb
<% @doctor.appointments.each do |appointment| %>
  <% if appointment.errors.any? %>
    <div style="color: red">
      <ul>
        <% appointment.errors.each do |error| %>
          <li><%= error.options[:message] %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

<div class="doc--header">
  <p class="doc--title">Dr. <%= @doctor.name %></p>
  <p class="doc--category"><%= @doctor.category.title %></p>
</div>

<div class="doc--btn">
  <% if current_patient.present? %>
    <%= button_to 'Book an appointment', doctor_appointments_path(@doctor), 
                                          class: "btn",
                                          method: :post %>
  <% end %>
</div>

  <% if current_doctor.present? %>
  <div class="doc--list">
    <% if @appointments.active.empty? %>
      <h3>You haven't upcoming Appointments</h3>
    <% else %>
      <h3>My coming Appointments</h3>
      <ol>
        <% @doctor.appointments.active.each do |appointment| %>
          <li>Patient's e-mail: <%= link_to appointment.patient.phone, doctor_appointment_path(@doctor.id, appointment.id) %></li>
        <% end %>
      </ol>
    <% end %>
  </div>

    <div class="doc--list">
    <% if @appointments.closed.empty? %>
      <h3>You haven't signed Appointments</h3>
    <% else %>
      <h3>My Signed Appointments</h3>
      <ol>
        <% @doctor.appointments.closed.each do |appointment| %>
          <li>
            Patient's e-mail: <%= appointment.patient.phone %>
            <div class="pat--docs">
              <p>Attached docs:</p>
              <%= image_tag(appointment.photo, width: 100) if appointment.photo.attached? %>
            </div>
          </li>
        <% end %>
      </ol>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodicaClinicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <%= render 'shared/navbar' %>
    </nav>
    <div class="container">
      <div class="notice-msg">
        <% if flash.notice %>
          <p class="notice"><%= notice %></p>
        <% elsif flash.alert %>
          <p class="alert"><%= alert %></p>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

<%= console %>

app/views/patients/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/patients/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:phone) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/patients/show.html.erb
<% @appointments.each do |appointment| %>
  <% if appointment.errors.any? %>
    <div style="color: red">
      <ul>
        <% appointment.errors.each do |error| %>
          <li><%= error.options[:message] %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

<div class="pat--list">
  <% if @appointments.active.empty? %>
    <h3>You haven't upcoming Appointments</h3>
  <% else %>
    <h3>My Coming Appointments</h3>
    <ul>
      <% @appointments.active.each do |appointment| %>
        <li>
          <div class="app-block">
            <p>Visit to: <%= appointment.doctor.category.title %></p>
            <p>Dr. <%= link_to appointment.doctor.name, doctor_path(appointment.doctor) %></p>
            <div class="doc--btn">
              <%= button_to 'Cancel an appointment', patient_appointment_path(current_patient.id, appointment.id), 
                                                  class: "btn", 
                                                  method: :patch %>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  <% end %>

  <% if @appointments.closed.empty? %>
    <h3>You haven't Closed Appointments</h3>
  <% else %>
    <h3>My Closed Appointments</h3>
    <ul>
      <% @appointments.closed.each do |appointment| %>
        <li>
          <div class="app-block">
            <p>Visit to: <%= appointment.doctor.category.title %></p>
            <p>Dr. <%= link_to appointment.doctor.name, doctor_path(appointment.doctor) %></p>
            <p>Recommendation: <%= appointment.recommendation %></p>
            <div class="pat--docs">
              <p>Attached docs:</p>
              <%= image_tag(appointment.photo, width: 100) if appointment.photo.attached? %>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="left-part">
  <h1><%= link_to 'CodicaClinic', root_path %></h1>
</div>
<div class="right-part">
  <% if current_patient.present? %>
    <span class="line">
      <%= link_to current_patient.phone, patient_path(current_patient) %>
      <%= button_to "Log out", destroy_patient_session_path, class: "btn--log-out", method: :delete %>
    </span>
  <% elsif current_doctor.present? %>
    <span class="line">
      <%= link_to "Dr. #{current_doctor.name}", doctor_path(current_doctor) %> 
      <%= button_to "Log out", destroy_doctor_session_path, class: "btn--log-out", method: :delete %>
    </span>
  <% else %>
    <p>Patients -> <%= link_to "Log in", new_patient_session_path %> | 
                   <%= link_to "Sign up", new_patient_registration_path %>
    </p>
    <p>Doctors -> <%= link_to "Log in", new_doctor_session_path %> </p>
  <% end %>
</div>